apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: app
spec:
  provider: aws
  # K8S SECRET OBJECT 
  secretObjects:
  - secretName: rds-password
    type: Opaque
    data: 
    - objectName: rds-password #FROM PARAMETERS BELOW
      key: rds_pwd
  # PARAMETERS TO PULL FROM AWS SECRET MANAGER
  parameters:
    objects: |
      - objectName: customer-a
        objectType: secretsmanager
        objectAlias: rds-password
